Update deploy-dev.yml

diff --git a/.github/workflows/deploy-dev.yml b/.github/workflows/deploy-dev.yml
--- a/.github/workflows/deploy-dev.yml
+++ b/.github/workflows/deploy-dev.yml
@@ -26,7 +26,7 @@ jobs:
 
     - name: Clean FTP directory
       run: |
-        lftp -c "set sftp:connect-program 'ssh -a -x'; open ftp://${{ secrets.FTP_JAVABACKENDSERVER }}; user ${{ secrets.FTP_JAVABACKENDUSERNAME }} ${{ secrets.FTP_JAVABACKENDPASSWORD }}; rm -f praticboutic_backend_java-0.0.1-SNAPSHOT.jar; bye"
+        lftp -c "set sftp:connect-program 'ssh -a -x'; open ftp://${{ secrets.FTP_JAVABACKENDSERVER }}; user ${{ secrets.FTP_JAVABACKENDUSERNAME }} ${{ secrets.FTP_JAVABACKENDPASSWORD }}; rm -f praticboutic_backend_java-0.0.1-SNAPSHOT.jar || echo 'File not found, skipping deletion.'; bye"
 
     - name: Deploy backend JAR via FTP
       run: |
